export const POST_HOG_CONSTANTS = {
  PROJECT_LOAD: "PROJECT_LOAD",
  RECIPE_SUBMIT: "RECIPE_SUBMIT",
  RECIPE_SUBMIT_SUCCESS: "RECIPE_SUBMIT_SUCCESS",
  RECIPE_SUBMIT_FAILURE: "RECIPE_SUBMIT_FAILURE",
  RECIPE_ABORT: "RECIPE_ABORT",
};
